name: Node.js CI

on:
  push:
    branches: [master, develop, release/*, bugfix/*, hotfix/*]
  pull_request:
    branches: [master, develop, release/*, bugfix/*, hotfix/*]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
